pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                // Dockerfile と hello.c が `docker/` ディレクトリにある場合
                // カレントディレクトリを `docker` ディレクトリに変更してからビルド
                dir('docker') {
                    bat 'docker build -t hello:latest .'
                }
                // もしくは、ビルドコンテキストのパスを明示的に指定する
                // bat 'docker build -t hello:latest docker' // リポジトリのルートから docker/ を指定
            }
        }
        stage('Run tests') {
            steps {
                // コンテナを実行して出力を確認
                bat 'docker run --rm hello:latest'
            }
        }
        stage('Push (optional)') {
            when {
                expression { return false } // 必要なら true にして registry へ push
            }
            steps {
                // 例: docker login と docker push の処理を入れる
                bat 'echo pushing...'
            }
        }
    }
    post {
        always {
            // ビルド後にローカルイメージをクリーンアップするなど
            bat 'docker image prune -f'
        }
    }
}
